services:
  app:
    build:
      context: .
      args:
        APP_URL: ${APP_URL}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        GOOGLE_OAUTH2_CALLBACK_URL: ${GOOGLE_OAUTH2_CALLBACK_URL}
        GOOGLE_CLIENT_STALKERS_API_SECRET: ${GOOGLE_CLIENT_STALKERS_API_SECRET}
        GOOGLE_CLIENT_STALKERS_API_HEADER: ${GOOGLE_CLIENT_STALKERS_API_HEADER}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_CDN_URL: ${NEXT_PUBLIC_CDN_URL}
        NEXT_PUBLIC_EVICT: ${NEXT_PUBLIC_EVICT}
        NEXT_PUBLIC_DOMAIN: ${NEXT_PUBLIC_DOMAIN}
        NEXT_PUBLIC_MAINTENANCE: ${NEXT_PUBLIC_MAINTENANCE}
        PUBLIC_KEY: ${PUBLIC_KEY}
    ports:
      - "3000:3000"
    env_file:
      - .env.local