/* eslint-disable react/no-unescaped-entities */

import PageHeader from "@/components/page-header";
import { generateBreadcrumbJsonLDSchema } from "@/lib/json-ld/bread-crumb-schema";
import { SirenIcon } from "lucide-react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy policy of our website",
};

const PrivacyPolicyPage = () => {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(generateBreadcrumbJsonLDSchema("Privacy Policy", "/privacy-policy")).replace(/</g, '\\u003c'),
        }}
      />
      <PageHeader
        icon={SirenIcon}
        title="Privacy Policy"
        description="Important, please read these privacy policy terms carefully."
        descriptionClassName="text-sm md:text-base max-w-3xl"
      />
      <div className="mb-8 rounded-lg border border-zinc-800 bg-secondary/10 p-6 sm:p-8">
        <p className="text-sm md:text-base leading-relaxed text-zinc-300">
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
          information when You respond to our advertisements and tells You about Your privacy rights and how the law
          protects You. We use Your Personal Data to contact and support you, as well as to provide and improve the
          Service. By using the Service, You agree to the collection and use of information in accordance with this
          Privacy Policy.
        </p>
      </div>

      <section className="mb-8">
        <h2 className="mb-6 text-lg md:text-3xl font-bold text-white">Interpretation and Definitions</h2>

        <div className="space-y-6">
          <div className="rounded-lg border border-zinc-800 bg-secondary/10 p-6">
            <h3 className="mb-4 text-base md:text-xl font-semibold text-red-800">Interpretation</h3>
            <p className="text-sm md:text-base leading-relaxed text-zinc-300">
              The words of which the initial letter is capitalized have meanings defined under the following
              conditions. The following definitions shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>
          </div>

          <div className="rounded-lg border border-zinc-800 bg-secondary/10 p-6">
            <h3 className="mb-4 text-base md:text-xl font-semibold text-red-800">Definitions</h3>
            <p className="mb-4 text-sm md:text-base leading-relaxed text-zinc-300">For the purposes of this Privacy Policy:</p>
            <ul className="space-y-3 text-zinc-300 text-sm md:text-base">
              <li className="leading-relaxed">
                <strong className="text-white">Company</strong> (referred to as either "the Company", "We", "Us" or
                "Our" in this Agreement) refers to <span className="text-red-800 font-semibold">DevilSect</span>.
              </li>
              <li className="leading-relaxed">
                <strong className="text-white">Device</strong> means any device that can access the Service such as a
                computer, a cellphone or a digital tablet.
              </li>
              <li className="leading-relaxed">
                <strong className="text-white">Personal Data</strong> is any information that relates to an identified
                or identifiable individual.
              </li>
              <li className="leading-relaxed">
                <strong className="text-white">Service</strong> refers to the advertisement, website, or application.
              </li>
              <li className="leading-relaxed">
                <strong className="text-white">Service Provider</strong> means any natural or legal person who
                processes the data on behalf of the Company. It refers to third-party companies or individuals
                employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to
                perform services related to the Service or to assist the Company in analyzing how the Service is used.
              </li>
              <li className="leading-relaxed">
                <strong className="text-white">Usage Data</strong> refers to data collected automatically, either
                generated by the use of the Service or from the Service infrastructure itself (for example, the
                duration of a page visit).
              </li>
              <li className="leading-relaxed">
                <strong className="text-white">You</strong> means the individual accessing or using the Service, or
                the company, or other legal entity on behalf of which such individual is accessing or using the
                Service, as applicable.
              </li>
            </ul>
          </div>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="mb-6 text-lg md:text-3xl font-bold text-white">Collecting and Using Your Personal Data</h2>

        <div className="space-y-6">
          <div className="rounded-lg border border-zinc-800 bg-secondary/10 p-6">
            <h3 className="mb-4 text-base md:text-xl font-semibold text-red-800">Types of Data Collected</h3>

            <h4 className="mb-3 md:text-lg font-semibold text-white">Personal Data</h4>
            <p className="mb-4 text-sm md:text-base leading-relaxed text-zinc-300">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information
              that can be used to contact or identify You. Personally identifiable information may include, but is not
              limited to:
            </p>
            <ul className="text-sm md:text-base space-y-2 text-zinc-300">
              <li className="leading-relaxed">First name and last name</li>
              <li className="leading-relaxed">Email address</li>
              <li className="leading-relaxed">Phone number</li>
              <li className="leading-relaxed">Location details such as your address, city, or country</li>
              <li className="leading-relaxed">
                Any other data such as personal preferences, requirements, or comments
              </li>
            </ul>
          </div>

          <div className="rounded-lg border border-zinc-800 bg-secondary/10 p-6">
            <h3 className="mb-4 text-base md:text-xl font-semibold text-red-800">Use of Your Personal Data</h3>
            <p className="mb-4 text-sm md:text-base leading-relaxed text-zinc-300">
              The Company may use Personal Data for the following purposes:
            </p>
            <ul className="text-sm md:text-base space-y-3 text-zinc-300">
              <li className="leading-relaxed">
                <strong className="text-white">To provide and maintain our Service,</strong> including to monitor the
                usage of our Service.
              </li>
              <li className="leading-relaxed">
                <strong className="text-white">To manage Your Account:</strong> to manage Your registration as a user
                of the Service. The Personal Data You provide can give You access to different functionalities of the
                Service that are available to You as a registered user.
              </li>
              <li className="leading-relaxed">
                <strong className="text-white">For the performance of a contract:</strong> the development, compliance
                and undertaking of the purchase contract for the products, items or services You have purchased or of
                any other contract with Us through the Service.
              </li>
              <li className="leading-relaxed">
                <strong className="text-white">To contact You:</strong> To contact You by email, telephone calls, SMS,
                or other equivalent forms of electronic communication, such as a mobile application's push
                notifications regarding updates or informative communications related to the functionalities, products
                or contracted services, including the security updates, when necessary or reasonable for their
                implementation.
              </li>
              <li className="leading-relaxed">
                <strong className="text-white">To provide You</strong> with news, special offers and general
                information about other goods, services and events which we offer that are similar to those that you
                have already purchased or enquired about unless You have opted not to receive such information.
              </li>
              <li className="leading-relaxed">
                <strong className="text-white">To manage Your requests:</strong> To attend and manage Your requests to
                Us.
              </li>
              <li className="leading-relaxed">
                <strong className="text-white">For business transfers:</strong> We may use Your information to
                evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale
                or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy,
                liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among
                the assets transferred.
              </li>
              <li className="leading-relaxed">
                <strong className="text-white">For other purposes:</strong> We may use Your information for other
                purposes, such as data analysis, identifying usage trends, determining the effectiveness of our
                promotional campaigns and to evaluate and improve our Service, products, services, marketing and your
                experience.
              </li>
            </ul>
          </div>

          <div className="rounded-lg border border-zinc-800 bg-secondary/10 p-6">
            <h3 className="mb-4 text-base md:text-xl font-semibold text-red-800">Sharing Your Personal Information</h3>
            <p className="mb-4 text-sm md:text-base leading-relaxed text-zinc-300">
              We may share Your personal information in the following situations:
            </p>
            <ul className="text-sm md:text-base space-y-3 text-zinc-300">
              <li className="leading-relaxed">
                <strong className="text-white">With Service Providers:</strong> We may share Your personal information
                with Service Providers to monitor and analyze the use of our Service, to contact You.
              </li>
              <li className="leading-relaxed">
                <strong className="text-white">For business transfers:</strong> We may share or transfer Your personal
                information in connection with, or during negotiations of, any merger, sale of Company assets,
                financing, or acquisition of all or a portion of Our business to another company.
              </li>
              <li className="leading-relaxed">
                <strong className="text-white">With Affiliates:</strong> We may share Your information with Our
                affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates
                include Our parent company and any other subsidiaries, joint venture partners or other companies that
                We control or that are under common control with Us.
              </li>
              <li className="leading-relaxed">
                <strong className="text-white">With business partners:</strong> We may share Your information with Our
                business partners to offer You certain products, services or promotions.
              </li>
              <li className="leading-relaxed">
                <strong className="text-white">With other users:</strong> when You share personal information or
                otherwise interact in the public areas with other users, such information may be viewed by all users
                and may be publicly distributed outside.
              </li>
              <li className="leading-relaxed">
                <strong className="text-white">With Your consent:</strong> We may disclose Your personal information
                for any other purpose with Your consent.
              </li>
            </ul>
          </div>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="mb-6 text-lg md:text-3xl font-bold text-white">Retention of Your Personal Data</h2>
        <div className="space-y-4 rounded-lg border border-zinc-800 bg-secondary/10 p-6">
          <p className="text-sm md:text-base leading-relaxed text-zinc-300">
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in
            this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our
            legal obligations (for example, if we are required to retain your data to comply with applicable laws),
            resolve disputes, and enforce our legal agreements and policies.
          </p>
          <p className="text-sm md:text-base leading-relaxed text-zinc-300">
            The Company will also retain Usage Data for internal analysis purposes.
          </p>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="mb-6 text-lg md:text-3xl font-bold text-white">Transfer of Your Personal Data</h2>
        <div className="space-y-4 rounded-lg border border-zinc-800 bg-secondary/10 p-6">
          <p className="text-sm md:text-base leading-relaxed text-zinc-300">
            Your information, including Personal Data, is processed at the Company's operating offices and in any
            other places where the parties involved in the processing are located. It means that this information may
            be transferred to — and maintained on — computers located outside of Your state, province, country or
            other governmental jurisdiction where the data protection laws may differ than those from Your
            jurisdiction.
          </p>
          <p className="text-sm md:text-base leading-relaxed text-zinc-300">
            Your consent to this Privacy Policy followed by Your submission of such information represents Your
            agreement to that transfer.
          </p>
          <p className="text-sm md:text-base leading-relaxed text-zinc-300">
            The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in
            accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an
            organization or a country unless there are adequate controls in place including the security of Your data
            and other personal information.
          </p>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="mb-6 text-lg md:text-3xl font-bold text-white">Disclosure of Your Personal Data</h2>

        <div className="space-y-6">
          <div className="rounded-lg border border-zinc-800 bg-secondary/10 p-6">
            <h3 className="mb-4 text-base md:text-xl font-semibold text-red-800">Law Enforcement</h3>
            <p className="text-sm md:text-base leading-relaxed text-zinc-300">
              Under certain circumstances, the Company may be required to disclose Your Personal Data if required to
              do so by law or in response to valid requests by public authorities (e.g. a court or a government
              agency).
            </p>
          </div>

          <div className="rounded-lg border border-zinc-800 bg-secondary/10 p-6">
            <h3 className="mb-4 text-base md:text-xl font-semibold text-red-800">Other Legal Requirements</h3>
            <p className="mb-4 text-sm md:text-base leading-relaxed text-zinc-300">
              The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
            </p>
            <ul className="text-sm md:text-base space-y-2 text-zinc-300">
              <li className="leading-relaxed">Comply with a legal obligation</li>
              <li className="leading-relaxed">Protect and defend the rights or property of the Company</li>
              <li className="leading-relaxed">
                Prevent or investigate possible wrongdoing in connection with the Service
              </li>
              <li className="leading-relaxed">Protect the personal safety of Users of the Service or the public</li>
              <li className="leading-relaxed">Protect against legal liability</li>
            </ul>
          </div>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="mb-6 text-lg md:text-3xl font-bold text-white">Security of Your Personal Data</h2>
        <div className="rounded-lg border border-zinc-800 bg-secondary/10 p-6">
          <p className="text-sm md:text-base leading-relaxed text-zinc-300">
            The security of Your Personal Data is important to Us, but remember that no method of transmission over
            the Internet, or method of electronic storage is 100% secure. While We strive to use commercially
            acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
          </p>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="mb-6 text-lg md:text-3xl font-bold text-white">Links to Other Websites</h2>
        <div className="rounded-lg border border-zinc-800 bg-secondary/10 p-6">
          <p className="mb-4 text-sm md:text-base leading-relaxed text-zinc-300">
            Our Service may contain links to other websites that are not operated by Us. If You click on a third party
            link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy
            of every site You visit.
          </p>
          <p className="text-sm md:text-base leading-relaxed text-zinc-300">
            We have no control over and assume no responsibility for the content, privacy policies or practices of any
            third party sites or services.
          </p>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="mb-6 text-lg md:text-3xl font-bold text-white">Changes to this Privacy Policy</h2>
        <div className="rounded-lg border border-zinc-800 bg-secondary/10 p-6">
          <p className="mb-4 text-sm md:text-base leading-relaxed text-zinc-300">
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new
            Privacy Policy on this page.
          </p>
          <p className="text-sm md:text-base leading-relaxed text-zinc-300">
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy
            are effective when they are posted on this page.
          </p>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="mb-6 text-lg md:text-3xl font-bold text-white">Contact Us</h2>
        <div className="rounded-lg border bg-secondary/10 p-6">
          <p className="text-sm md:text-base leading-relaxed text-zinc-300">
            If you have any questions about this Privacy Policy, You can contact us via email at{" "}
            <a
              href="mailto:contact@devilsect.com"
              className="font-semibold text-red-800 hover:text-red-900 transition-colors"
            >
              contact@devilsect.com
            </a>
          </p>
        </div>
      </section>
    </>
  )
}

export default PrivacyPolicyPage;
